[package]
name = "no-incode-comments"
version = "0.1.0"
edition = "2024"

[lib]
proc-macro = true

[dependencies]
pulldown-cmark = "0.13.0"
syn = { version = "2", features = ["full", "extra-traits", "parsing"] }
quote = "1"
proc-macro2 = "1"
toml = "0.8"
